### ISSUE TITLE
you removed ntlk setup

### ISSUE THREAD

**Issue by behrica** [openefsa/foodex2-sca-backend#5]
Are you sure, this tow lines are not needed ?

A fresh installed NLTK package does not have the models downloaded.
I added it, because I saw it failing in teh docker run.

https://github.com/openefsa/foodex2-sca-backend/blob/dfa5b304280c5b95cd07820eca902fee75cc9f10/Dockerfile#L10

**Comment by AlbSha** [comment]
yeap no need it since now is used a custom list of stop words.
