### ISSUE TITLE
Json data format

### ISSUE THREAD

**Issue by joachimakerlind** [openefsa/foodex2-sca-backend#6]
We have a question regarding the format of the json data that the Foodex2 application returns.
In this screenshot of the data…

![JsonFormat](https://user-images.githubusercontent.com/16782913/109020736-84dcf580-76ba-11eb-85cf-97a4ae7e1f30.jpg)

…you see that the termCode is used as the name of the object in the json structure.
This makes it hard to programmatically parse the data because the json structure is dynamic.

We believe that it instead each model should contain an object with a generic name or, if needed, an array of objects so that it can be matched with a predefined data structure.

Is the data structured this way intentionally for some reason?

Kind regards.
Joachim

**Comment by behrica** [comment]
In my view the model predicts various base terms, each with a certain probability.
In fact, it predicts any base code with a certain probability.

Then we have decided to return only the predictions above a given score, (the threshold which  you add to the call)
and this leads to the structure of the response.
This makes it dynamic, if  you mean this.

But is is still  easy to parse, I would say, being 2 level deep nested json objects.
Specially the "depth" is fixed.


I suppose that C# has a way to convert the above json into a dictionary,
where each baseterm becomes a key and the information per baseterm is a certain custom object (or on other dictionary)

We do this in our frontend in JS

https://github.com/openefsa/foodex2-sca-frontend/blob/5969ca258235cbb8a1c98747962f1955cf4c9721/src/components/baseterms-component.js#L25

**Comment by AlbSha** [comment]
new json structure available
